### ISSUE TITLE
[bug]: it is now safe to delete a broker with locked funds

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/near-storage-bridge#16]
**Describe the bug**
Before, it was not safe to remove a broker with locked funds associated with it. This is no longer the case. We should remove the constraint in deleteBroker, as this complicates things, and is no longer necessary.

**To Reproduce**
Add a broker, lock some funds with them, and then try to delete them. The contract call will fail, even though it really doesn't need to.

**Expected behavior**
This should just be allowed. If you delete a broker with locked funds associated with it, that broker will still eventually receive their share once the funds are released, regardless of if they are still in the broker map or not.

**Comment by asutula** [comment]
How does the contract know the address of the broker to send their share to if there is no record of the broker? Is the broker address tracked in the deposit record?

**Comment by carsonfarmer** [comment]
Yes, exactly.
